<a href="https://colab.research.google.com/github/Raju-kushwaha1230/ML/blob/main/fucntion_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **function transformer**
---
- log transform
- Recipro
- sq/sqrt
- custom

# **Power Transformer**
---
- Box-Ox
- yeo-Johnson

#How to find if data is normal?
- sns.distplot - gives distribution.
- pd.skew()- if 0 then good if negative and negative then wronge.
- QQplot - reliableway tofind data is normalor not .

#log Transform
- used when data is right skew data .
- can't use on negative values

#sq transform (x^2)
- used when data is left skew data.

In [44]:
import numpy as np
import pandas as pd

In [45]:
# df = pd.read_csv("/content/cars.csv", usecols=['km_driven','selling_price'])
df = pd.read_csv('/content/train.csv', usecols=['Age','Survived','Fare'])

In [46]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [47]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [48]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

/tmp/ipykernel_2871/1119855726.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.mean of 0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Age'].fillna(df['Age'].mean, inplace=True)

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X = df.iloc[:,1:3]
y = df.iloc[:,0]

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [55]:
X_test

RecursionError: maximum recursion depth exceeded

RecursionError: maximum recursion depth exceeded

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

In [16]:
clf = LinearRegression()
clf2 = DecisionTreeRegressor()

In [23]:
X_train_transform =

TypeError: Series.transform() missing 1 required positional argument: 'func'

In [24]:
df

      km_driven  selling_price
0        145500         450000
1        120000         370000
2        140000         158000
3        127000         225000
4        120000         130000
...         ...            ...
8123     110000         320000
8124     119000         135000
8125     120000         382000
8126      25000         290000
8127      25000         290000

[8128 rows x 2 columns]