<a href="https://colab.research.google.com/github/Raju-kushwaha1230/ML/blob/main/without%20using%20pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pipeline in ML**
Pipeline chains together multiple steps so that the output of each step is used as input to the next step

In [146]:
import pandas as pd
import numpy as np

In [147]:
df = pd.read_csv('/content/train.csv')

In [148]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [149]:
df = df.drop(columns = ['Name','PassengerId','Ticket','Cabin'])

In [150]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [151]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [152]:
from sklearn.model_selection import train_test_split

In [153]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size=0.2, random_state=0)

In [154]:
X_train

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S
817       2    male  31.0      1      1  37.0042        C
378       3    male  20.0      0      0   4.0125        C
491       3    male  21.0      0      0   7.2500        S
..      ...     ...   ...    ...    ...      ...      ...
835       1  female  39.0      1      1  83.1583        C
192       3  female  19.0      1      0   7.8542        S
629       3    male   NaN      0      0   7.7333        Q
559       3  female  36.0      1      0  17.4000        S
684       2    male  60.0      1      1  39.0000        S

[712 rows x 7 columns]

In [155]:
from sklearn.impute import SimpleImputer

In [156]:
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

In [157]:
X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.fit_transform(X_test[['Age']])
X_test_embarked = si_embarked.fit_transform(X_test[['Embarked']])

In [158]:
X_train_age, X_train_embarked

(array([[29.74518389],
        [31.        ],
        [31.        ],
        [20.        ],
        [21.        ],
        [45.5       ],
        [22.        ],
        [29.74518389],
        [29.74518389],
        [26.        ],
        [25.        ],
        [21.        ],
        [31.        ],
        [15.        ],
        [29.74518389],
        [29.74518389],
        [65.        ],
        [29.74518389],
        [ 1.        ],
        [34.        ],
        [49.        ],
        [18.        ],
        [29.74518389],
        [70.        ],
        [14.        ],
        [19.        ],
        [30.        ],
        [31.        ],
        [32.        ],
        [16.        ],
        [50.        ],
        [24.        ],
        [56.        ],
        [ 7.        ],
        [ 9.        ],
        [33.        ],
        [19.        ],
        [32.5       ],
        [ 1.        ],
        [45.        ],
        [29.74518389],
        [19.        ],
        [21.        ],
        [ 4.        ],
        [28.        ],
        [17.        ],
        [30.        ],
        [22.        ],
        [45.        ],
        [25.        ],
        [18.        ],
        [33.        ],
        [24.        ],
        [26.        ],
        [22.        ],
        [56.        ],
        [28.        ],
        [35.        ],
        [ 6.        ],
        [41.        ],
        [29.74518389],
        [29.74518389],
        [52.        ],
        [32.        ],
        [35.        ],
        [18.        ],
        [29.74518389],
        [29.74518389],
        [29.74518389],
        [29.74518389],
        [27.        ],
        [22.        ],
        [16.        ],
        [49.        ],
        [29.74518389],
        [16.        ],
        [18.        ],
        [29.74518389],
        [45.        ],
        [ 3.        ],
        [70.5       ],
        [29.74518389],
        [29.74518389],
        [34.5       ],
        [40.        ],
        [29.74518389],
        [27.        ],
        [18.        ],
        [29.74518389],
        [51.        ],
        [49.        ],
        [ 1.        ],
        [54.        ],
        [29.74518389],
        [ 8.        ],
        [24.        ],
        [20.        ],
        [30.        ],
        [24.        ],
        [29.74518389],
        [29.74518389],
        [25.        ],
        [29.74518389],
        [29.74518389],
        [48.        ],
        [74.        ],
        [23.        ],
        [17.        ],
        [29.74518389],
        [52.        ],
        [29.74518389],
        [29.74518389],
        [34.        ],
        [29.74518389],
        [34.        ],
        [24.        ],
        [29.        ],
        [36.        ],
        [61.        ],
        [45.        ],
        [34.        ],
        [29.74518389],
        [21.        ],
        [29.74518389],
        [ 0.83      ],
        [26.        ],
        [29.74518389],
        [55.        ],
        [ 6.        ],
        [50.        ],
        [26.        ],
        [34.        ],
        [39.        ],
        [30.        ],
        [29.74518389],
        [22.        ],
        [35.        ],
        [42.        ],
        [29.        ],
        [29.74518389],
        [31.        ],
        [29.74518389],
        [29.74518389],
        [41.        ],
        [28.        ],
        [46.        ],
        [29.74518389],
        [50.        ],
        [38.        ],
        [11.        ],
        [20.        ],
        [35.        ],
        [39.        ],
        [ 9.        ],
        [19.        ],
        [40.        ],
        [38.        ],
        [22.        ],
        [65.        ],
        [60.        ],
        [47.        ],
        [29.74518389],
        [51.        ],
        [21.        ],
        [27.        ],
        [27.        ],
        [49.        ],
        [29.        ],
        [16.        ],
        [21.        ],
        [47.        ],
        [58.        ],
        [40.        ],
        [35.        ],
        [51.        ],
        [27.        ],
        [33.        ],
        [ 4.        ],
        [28.        ],
        [34.        ],
        [43.        ],
        [29.74518389],
        [29.74518389],
        [39.        ],
        [29.74518389],
        [18.        ],
        [30.        ],
        [23.        ],
        [16.        ],
        [26.        ],
        [30.        ],
        [18.        ],
        [ 8.        ],
        [55.        ],
        [44.        ],
        [29.74518389],
        [54.        ],
        [30.        ],
        [20.        ],
        [ 2.        ],
        [37.        ],
        [29.74518389],
        [29.74518389],
        [16.        ],
        [19.        ],
        [21.        ],
        [29.        ],
        [29.74518389],
        [29.74518389],
        [15.        ],
        [ 3.        ],
        [29.74518389],
        [32.        ],
        [32.        ],
        [29.        ],
        [29.74518389],
        [48.        ],
        [ 2.        ],
        [23.        ],
        [32.        ],
        [29.        ],
        [28.5       ],
        [29.74518389],
        [29.74518389],
        [44.        ],
        [26.        ],
        [21.        ],
        [36.        ],
        [47.        ],
        [ 5.        ],
        [21.        ],
        [30.        ],
        [28.        ],
        [26.        ],
        [29.        ],
        [29.74518389],
        [24.        ],
        [32.        ],
        [29.74518389],
        [71.        ],
        [71.        ],
        [29.74518389],
        [41.        ],
        [36.        ],
        [32.        ],
        [24.        ],
        [18.        ],
        [36.        ],
        [33.        ],
        [22.        ],
        [29.74518389],
        [ 4.        ],
        [28.        ],
        [24.        ],
        [36.        ],
        [29.        ],
        [29.74518389],
        [57.        ],
        [29.        ],
        [39.        ],
        [29.74518389],
        [44.        ],
        [36.        ],
        [ 1.        ],
        [21.        ],
        [61.        ],
        [38.        ],
        [30.        ],
        [47.        ],
        [24.        ],
        [27.        ],
        [25.        ],
        [21.        ],
        [19.        ],
        [12.        ],
        [23.        ],
        [29.74518389],
        [20.        ],
        [ 4.        ],
        [40.        ],
        [14.        ],
        [30.        ],
        [17.        ],
        [38.        ],
        [29.74518389],
        [57.        ],
        [53.        ],
        [18.        ],
        [29.74518389],
        [26.        ],
        [51.        ],
        [40.        ],
        [35.        ],
        [25.        ],
        [36.        ],
        [28.        ],
        [35.        ],
        [29.74518389],
        [20.        ],
        [29.74518389],
        [24.        ],
        [33.        ],
        [18.        ],
        [34.        ],
        [18.        ],
        [47.        ],
        [30.        ],
        [19.        ],
        [22.        ],
        [25.        ],
        [29.74518389],
        [24.        ],
        [36.        ],
        [38.        ],
        [45.        ],
        [10.        ],
        [19.        ],
        [41.        ],
        [35.        ],
        [17.        ],
        [29.74518389],
        [20.        ],
        [29.74518389],
        [ 4.        ],
        [35.        ],
        [29.74518389],
        [22.        ],
        [40.        ],
        [ 8.        ],
        [25.        ],
        [18.        ],
        [22.        ],
        [25.        ],
        [32.        ],
        [29.74518389],
        [50.        ],
        [47.        ],
        [80.        ],
        [37.        ],
        [ 2.        ],
        [29.74518389],
        [33.        ],
        [20.        ],
        [16.        ],
        [ 3.        ],
        [29.74518389],
        [25.        ],
        [40.5       ],
        [25.        ],
        [46.        ],
        [29.74518389],
        [23.        ],
        [21.        ],
        [39.        ],
        [23.        ],
        [29.74518389],
        [39.        ],
        [29.74518389],
        [16.        ],
        [29.74518389],
        [39.        ],
        [29.74518389],
        [38.        ],
        [35.        ],
        [17.        ],
        [29.        ],
        [11.        ],
        [29.        ],
        [29.74518389],
        [29.74518389],
        [30.5       ],
        [52.        ],
        [21.        ],
        [24.        ],
        [24.        ],
        [29.74518389],
        [30.        ],
        [29.74518389],
        [16.        ],
        [ 3.        ],
        [22.        ],
        [35.        ],
        [27.        ],
        [48.        ],
        [15.        ],
        [29.74518389],
        [17.        ],
        [29.74518389],
        [25.        ],
        [30.        ],
        [ 0.83      ],
        [45.        ],
        [29.74518389],
        [29.74518389],
        [28.        ],
        [28.        ],
        [21.        ],
        [33.        ],
        [39.        ],
        [54.        ],
        [29.        ],
        [45.        ],
        [44.        ],
        [29.74518389],
        [29.74518389],
        [32.        ],
        [20.        ],
        [58.        ],
        [19.        ],
        [45.        ],
        [ 1.        ],
        [21.        ],
        [ 2.        ],
        [19.        ],
        [31.        ],
        [36.        ],
        [16.        ],
        [ 9.        ],
        [25.        ],
        [31.        ],
        [34.        ],
        [32.        ],
        [26.        ],
        [17.        ],
        [28.        ],
        [31.        ],
        [29.74518389],
        [44.        ],
        [ 4.        ],
        [18.        ],
        [23.        ],
        [33.        ],
        [30.        ],
        [48.        ],
        [38.        ],
        [26.        ],
        [24.        ],
        [26.        ],
        [ 2.        ],
        [27.        ],
        [ 2.        ],
        [27.        ],
        [22.        ],
        [29.74518389],
        [17.        ],
        [28.        ],
        [29.74518389],
        [29.74518389],
        [29.74518389],
        [29.74518389],
        [29.74518389],
        [22.        ],
        [36.        ],
        [18.        ],
        [18.        ],
        [25.        ],
        [36.        ],
        [19.        ],
        [13.        ],
        [16.        ],
        [41.        ],
        [29.74518389],
        [26.        ],
        [18.        ],
        [ 6.        ],
        [59.        ],
        [48.        ],
        [66.        ],
        [23.        ],
        [19.        ],
        [24.        ],
        [38.        ],
        [29.74518389],
        [24.        ],
        [32.        ],
        [29.74518389],
        [24.        ],
        [ 2.        ],
        [26.        ],
        [23.        ],
        [29.74518389],
        [32.        ],
        [ 9.        ],
        [34.        ],
        [36.        ],
        [30.        ],
        [36.        ],
        [42.        ],
        [22.        ],
        [48.        ],
        [21.        ],
        [43.        ],
        [29.74518389],
        [21.        ],
        [16.        ],
        [22.        ],
        [34.        ],
        [19.        ],
        [70.        ],
        [24.        ],
        [30.5       ],
        [24.        ],
        [19.        ],
        [ 8.        ],
        [ 1.        ],
        [27.        ],
        [45.        ],
        [42.        ],
        [14.5       ],
        [29.74518389],
        [26.        ],
        [64.        ],
        [29.74518389],
        [29.74518389],
        [56.        ],
        [52.        ],
        [29.74518389],
        [40.5       ],
        [22.        ],
        [ 0.75      ],
        [61.        ],
        [29.74518389],
        [29.74518389],
        [18.        ],
        [31.        ],
        [36.        ],
        [ 4.        ],
        [29.        ],
        [29.74518389],
        [38.        ],
        [47.        ],
        [42.        ],
        [55.5       ],
        [39.        ],
        [44.        ],
        [42.        ],
        [34.        ],
        [29.74518389],
        [24.        ],
        [29.74518389],
        [22.        ],
        [42.        ],
        [37.        ],
        [36.        ],
        [29.74518389],
        [27.        ],
        [29.74518389],
        [31.        ],
        [23.5       ],
        [35.        ],
        [19.        ],
        [59.        ],
        [47.        ],
        [31.        ],
        [65.        ],
        [30.        ],
        [29.74518389],
        [29.74518389],
        [29.74518389],
        [ 4.        ],
        [18.        ],
        [29.74518389],
        [31.        ],
        [63.        ],
        [62.        ],
        [ 9.        ],
        [29.74518389],
        [22.        ],
        [17.        ],
        [58.        ],
        [ 3.        ],
        [16.        ],
        [29.74518389],
        [47.        ],
        [ 5.        ],
        [27.        ],
        [29.74518389],
        [28.        ],
        [40.        ],
        [36.5       ],
        [29.74518389],
        [37.        ],
        [32.5       ],
        [23.        ],
        [16.        ],
        [34.        ],
        [27.        ],
        [33.        ],
        [42.        ],
        [28.        ],
        [29.74518389],
        [62.        ],
        [25.        ],
        [36.        ],
        [35.        ],
        [29.74518389],
        [29.74518389],
        [22.        ],
        [39.        ],
        [36.        ],
        [36.        ],
        [31.        ],
        [29.74518389],
        [30.        ],
        [42.        ],
        [29.74518389],
        [44.        ],
        [21.        ],
        [28.        ],
        [39.        ],
        [ 0.92      ],
        [29.74518389],
        [22.        ],
        [33.        ],
        [16.        ],
        [20.5       ],
        [50.        ],
        [19.        ],
        [29.74518389],
        [20.        ],
        [30.        ],
        [29.74518389],
        [54.        ],
        [29.74518389],
        [45.5       ],
        [17.        ],
        [29.74518389],
        [24.        ],
        [29.74518389],
        [23.        ],
        [20.        ],
        [29.74518389],
        [28.        ],
        [43.        ],
        [ 2.        ],
        [19.        ],
        [28.5       ],
        [27.        ],
        [30.        ],
        [20.        ],
        [25.        ],
        [29.74518389],
        [26.        ],
        [29.74518389],
        [29.74518389],
        [37.        ],
        [28.        ],
        [30.        ],
        [17.        ],
        [29.        ],
        [15.        ],
        [29.74518389],
        [11.        ],
        [29.74518389],
        [ 1.        ],
        [29.74518389],
        [29.        ],
        [18.        ],
        [22.        ],
        [30.        ],
        [52.        ],
        [32.        ],
        [50.        ],
        [29.74518389],
        [29.74518389],
        [36.        ],
        [42.        ],
        [28.        ],
        [ 9.        ],
        [58.        ],
        [31.        ],
        [24.        ],
        [50.        ],
        [34.        ],
        [ 4.        ],
        [ 5.        ],
        [29.74518389],
        [35.        ],
        [29.74518389],
        [ 0.67      ],
        [21.        ],
        [ 5.        ],
        [21.        ],
        [42.        ],
        [30.        ],
        [18.        ],
        [29.74518389],
        [28.        ],
        [56.        ],
        [29.74518389],
        [27.        ],
        [35.        ],
        [39.        ],
        [43.        ],
        [31.        ],
        [24.        ],
        [33.        ],
        [32.        ],
        [49.        ],
        [27.        ],
        [48.        ],
        [29.74518389],
        [50.        ],
        [14.        ],
        [29.74518389],
        [42.        ],
        [36.        ],
        [39.        ],
        [19.        ],
        [29.74518389],
        [36.        ],
        [60.        ]]),
 array([['C'],
        ['S'],
        ['C'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['Q'],
        ['Q'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['Q'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['C'],
        ['C'],
        ['S'],
        ['Q'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['Q'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['Q'],
        ['C'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['Q'],
        ['S'],
        ['Q'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['Q'],
        ['S'],
        ['Q'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['Q'],
        ['S'],
        ['Q'],
        ['C'],
        ['Q'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['S'],
        ['C'],
        ['S'],
        ['S'],
        ['C'],
        ['C'],
        ['C'],

In [159]:
from sklearn.preprocessing import OneHotEncoder

In [160]:
ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.fit_transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.fit_transform(X_test_embarked)

In [161]:
X_train_sex

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [162]:
X_train_rem = X_train.drop(columns=['Age','Sex','Embarked'])
X_test_rem = X_test.drop(columns=['Age','Sex','Embarked'])

In [163]:
X_train_transformed = np.concatenate((X_train_rem, X_train_sex, X_train_age,X_train_embarked), axis=1)
X_test_transformed = np.concatenate((X_test_rem, X_test_sex, X_test_age,X_test_embarked), axis=1)

In [164]:
X_train_transformed

array([[3., 0., 2., ..., 1., 0., 0.],
       [2., 0., 0., ..., 0., 0., 1.],
       [2., 1., 1., ..., 1., 0., 0.],
       ...,
       [3., 0., 0., ..., 0., 1., 0.],
       [3., 1., 0., ..., 0., 0., 1.],
       [2., 1., 1., ..., 0., 0., 1.]])

In [165]:
X_train_transformed.shape

(712, 10)

In [166]:
from sklearn.tree import DecisionTreeClassifier

In [167]:
clf = DecisionTreeClassifier()

In [168]:
clf.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [169]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1])

In [170]:
from sklearn.metrics import accuracy_score

In [171]:
accuracy_score(y_test, y_pred)

0.7821229050279329

In [172]:
import pickle

In [173]:
import os
os.makedirs('models', exist_ok=True)

In [174]:
pickle.dump(ohe_sex, open('models/ohe_sex.pkl', 'wb'))
pickle.dump(ohe_embarked, open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf, open('models/clf.pkl', 'wb'))

In [175]:
# import shutil
# from google.colab import files

# # Create a zip archive of the 'models' directory
# shutil.make_archive('models', 'zip', 'models')

# # Offer the zip file for download
# files.download('models.zip')

# **Predict the model without using Pipeline**

In [176]:
ohe_sex1 = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked1 = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
clf1 = pickle.load(open('models/clf.pkl','rb'))

In [206]:
#Pclass	Sex	Age	SibSp	Parch	Fare	Embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'], dtype=object).reshape(1,7)

In [207]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [208]:
test_input_sex = ohe_sex1.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [209]:
test_input_sex

array([[0., 1.]])

In [210]:
test_input_embarked= ohe_embarked1.transform(test_input[:,-1].reshape(1,1))

In [211]:
test_input_age = test_input[:,2].reshape(1,1)

In [212]:
test_input_transformed = np.concatenate((test_input[:,[0, 3, 4, 5]],test_input_age,test_input_sex, test_input_embarked), axis=1)

In [213]:
test_input_transformed.shape

(1, 10)

In [214]:
clf.predict(test_input_transformed)

array([0])